name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: touch output/images/hi.txt

    - name: create release
      run: gh release create ${{ github.ref }} output/images/hi.txt

